project:
  type: book

book:
  title: "Serological Data Analysis"
  author: 
    - name: "Dionne Argyropoulos, PhD"
    - orcid: 0000-0002-8068-0215
    - url: https://github.com/dionnecargy
  page-navigation: true
  page-footer: 
    background: light
    center: "Copyright 2026, VISPA"
  # cover-image: _brand/vispa_logo_only.png
  sidebar:
    search: true
    style: docked
    logo:  _brand/vispa_logo_only.png
    tools:
      - icon: globe
        href: https://vispa.online/
      - icon: github
        href: https://github.com/vispa-malaria
      - icon: envelope-fill
        href: https://vispa.online/contact-us/
  favicon: _brand/vispa_logo_only.png
  search: true
  chapters:
      - index.qmd
      - code/intro.qmd
      - part: "Tutorials"
        chapters: 
          - code/pvseroapp.qmd
          - code/pkpvpf.qmd
          - code/pvldh.qmd
      - part: "Data Exploration"
        chapters:
          - code/std_curves.qmd
          - code/mfi_rau.qmd
          - code/classification.qmd
  appendices:
    - code/tools.qmd
    - code/resources.qmd
    # - code/plotting.qmd
    - code/FAQs.qmd

bibliography: references.bib

format:
  html:
    toc: true
    toc-location: left
    toc-depth: 3
    self-contained: false
    grid:
      body-width: 1000px
      margin-width: 20px
      sidebar-width: 300px
    theme: 
      light: _brand/theme_custom.scss
      dark: _brand/theme_custom_dark.scss
    code-fold: false
    fig-width: 10
    fig-height: 5
    fig-dpi: 200
    code-summary: "Show code"
    code-tools:
      source: true
      toggle: false
      caption: none
    code-overflow: wrap
    highlight-style: _brand/textmate.theme
    number-sections: true

filters:
  - iconify